apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p7yixxk3h-python
  janus-idp.io/tekton: p7yixxk3h-python
  backstage.io/kubernetes-id: p7yixxk3h-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p7yixxk3h-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
